[package]
name = "simple_transcribe_rs"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "Audio to text transcription library written in rust that utilizes whisper-rs bindings."
homepage = "https://github.com/Marble879/SimpleTranscribe-rs"
repository = "https://github.com/Marble879/SimpleTranscribe-rs"
readme = "README.md"
keywords = ["STT", "Speech-to-text", "whisper", "openai", "transcription"]
categories = ["multimedia::audio"]
exclude = [".github"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whisper-rs = "0.14"
reqwest = "0.12"
tokio = { version = "1.44", features = ["full"] }
phf = { version = "0.11", features = ["macros"] }
symphonia = { version = "0.5", features = ["mp3"] }

[dev-dependencies]
tempfile = "3.19"
